/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Player = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
  'isIT' : IDL.Bool,
  'playerId' : IDL.Text,
  'color' : IDL.Text,
  'playerName' : IDL.Text,
  'isAlive' : IDL.Bool,
});
export const RoomView = IDL.Record({
  'status' : IDL.Text,
  'mapSeed' : IDL.Int,
  'lastActivity' : IDL.Int,
  'gameDuration' : IDL.Int,
  'players' : IDL.Vec(Player),
  'selectedMapType' : IDL.Text,
  'timeRemaining' : IDL.Int,
  'hostId' : IDL.Text,
  'roomCode' : IDL.Text,
});

export const idlService = IDL.Service({
  'createRoom' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
      [RoomView],
      [],
    ),
  'getAllRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
  'getRoomState' : IDL.Func([IDL.Text], [IDL.Opt(RoomView)], ['query']),
  'joinRoom' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(RoomView)],
      [],
    ),
  'kickPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'leaveRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'startGame' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateRoomSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Player = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
    'isIT' : IDL.Bool,
    'playerId' : IDL.Text,
    'color' : IDL.Text,
    'playerName' : IDL.Text,
    'isAlive' : IDL.Bool,
  });
  const RoomView = IDL.Record({
    'status' : IDL.Text,
    'mapSeed' : IDL.Int,
    'lastActivity' : IDL.Int,
    'gameDuration' : IDL.Int,
    'players' : IDL.Vec(Player),
    'selectedMapType' : IDL.Text,
    'timeRemaining' : IDL.Int,
    'hostId' : IDL.Text,
    'roomCode' : IDL.Text,
  });
  
  return IDL.Service({
    'createRoom' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
        [RoomView],
        [],
      ),
    'getAllRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
    'getRoomState' : IDL.Func([IDL.Text], [IDL.Opt(RoomView)], ['query']),
    'joinRoom' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(RoomView)],
        [],
      ),
    'kickPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'leaveRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'startGame' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateRoomSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };