/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Player {
  'x' : number,
  'y' : number,
  'z' : number,
  'isIT' : boolean,
  'playerId' : string,
  'color' : string,
  'playerName' : string,
  'isAlive' : boolean,
}
export interface RoomView {
  'status' : string,
  'mapSeed' : bigint,
  'lastActivity' : bigint,
  'gameDuration' : bigint,
  'players' : Array<Player>,
  'selectedMapType' : string,
  'timeRemaining' : bigint,
  'hostId' : string,
  'roomCode' : string,
}
export interface _SERVICE {
  'createRoom' : ActorMethod<
    [string, string, string, string, bigint, bigint, string],
    RoomView
  >,
  'getAllRooms' : ActorMethod<[], Array<RoomView>>,
  'getRoomState' : ActorMethod<[string], [] | [RoomView]>,
  'joinRoom' : ActorMethod<[string, string, string, string], [] | [RoomView]>,
  'kickPlayer' : ActorMethod<[string, string, string], boolean>,
  'leaveRoom' : ActorMethod<[string, string], boolean>,
  'startGame' : ActorMethod<[string, string, bigint, string], boolean>,
  'updateRoomSettings' : ActorMethod<[string, string, bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];